### ISSUE TITLE
Multible problems.

### ISSUE THREAD

**Issue by Rj248** [bluecreeper111/JEssentials#10]
1.14 The plugin breaks most of the vanilla Minecraft commands. Most of the commands it adds either work or don't work and the ones that do work show the message of it not working. sudo command is broken and just says "/sudo" in chat. vanish command works but it says it doesn't work and the player vanishing doesn't have any confirmation that they have vanished.

I'm sure there are other problems that I don't know about.

![image](https://user-images.githubusercontent.com/39466898/57325271-acbf2b80-70d7-11e9-9b68-17db68718cd1.png)

Edit: /chatclear is broken

Edit 2: Found solution for vanilla commands do "/execute run" and add the command you want to use, example: "/execute run tp @a @s"

**Comment by jeremy-carefoot** [comment]
Do you have the plugin Vault installed?

**Comment by Rj248** [comment]
> 
> 
> Do you have the plugin Vault installed?

No, because it isn't on 1.14 yet.

**Comment by jeremy-carefoot** [comment]
Thats the problem. Though Vault says it doesn't support 1.14, I have tested it and it works. Please install it.
