### ISSUE TITLE
Vault Economy Null 1.14

### ISSUE THREAD

**Issue by S019** [bluecreeper111/JEssentials#11]
Running Spigot 1.14 R0.1 SNAPSHOT, Vault 1.7.2 b107

When the built in economy is enabled Vault displays the economy plugin as null when doing /vault-info 
![image](https://user-images.githubusercontent.com/7799596/57472256-04d26b00-725b-11e9-9ef3-a1f545d8da01.png)

**Comment by jeremy-carefoot** [comment]
Does the economy still work? This may be because I didn't specify a name for the economy.

**Comment by S019** [comment]
Yes as far as I can tell everything functions as intended. Just had me thinking it wasn't going to handle other Vault supported plugins.

**Comment by jeremy-carefoot** [comment]
It should, but if you run into any problems, just let me know.

**Comment by farmermoonshine** [comment]
vault locks into chat luckperms not ChatManager been told this is not a problem with CM but with vault, any idea?
