### ISSUE TITLE
command /enchant something wrong

### ISSUE THREAD

**Issue by Kritin26110** [bluecreeper111/JEssentials#15]
I have to use /enchant it's not auto command ,such as /enchant Unbreaking <level> and more
when i type it's like this /enchant MyName MyName MyName .... and more long command
that auto wrong command /enchant PlayerName list in game. It's not enchant list (unbreaking, smite, fortune,...)
You can fix this?

-Just Essentials v.1.4.0
-minecraft 1.14.1

**Comment by jeremy-carefoot** [comment]
I am not sure if what you are describing is a feature of the /enchant command.
