### ISSUE TITLE
"You are not a player!" spam to console

### ISSUE THREAD

**Issue by masonmanley** [bluecreeper111/JEssentials#18]
Just essentials results in the following being spammed to console:

29.05 12:03:27 [Server] INFO You are not a player!
29.05 12:03:57 [Server] INFO You are not a player!
29.05 12:04:27 [Server] INFO You are not a player!
29.05 12:04:58 [Server] INFO You are not a player!
29.05 12:05:28 [Server] INFO You are not a player!
29.05 12:05:58 [Server] INFO You are not a player!
29.05 12:06:29 [Server] INFO You are not a player!
29.05 12:06:59 [Server] INFO You are not a player!
29.05 12:07:29 [Server] INFO You are not a player!

**Comment by jeremy-carefoot** [comment]
Is your console set to automatically run commands? Those messages are only generated when a command is run from the Just Essentials plugin, and it cannot be from console.
