### ISSUE TITLE
Request: /return command

### ISSUE THREAD

**Issue by masonmanley** [bluecreeper111/JEssentials#19]
When staff or players in general use /tp (or a variant) it would be awesome to have a way for them to easily return to where they were before TPing using /return to get themselves back to their previous position which had been saved by the plugin.

This should be fairly simple to implement and I hope you can do it! Thanks

**Comment by jeremy-carefoot** [comment]
I have had multiple requests for this. It will be inside of the /back command in the next update. Thanks!
