### ISSUE TITLE
Permissions 

### ISSUE THREAD

**Issue by deezaath** [bluecreeper111/JEssentials#2]
How can i set permissions for players?
by default players cant go /spawn /home etc. can you help?

**Comment by jeremy-carefoot** [comment]
All permissions for the plugin can be found [here](https://github.com/bluecreeper111/JEssentials/wiki/Permissions).
To assign permissions to player's, you must download a permissions plugin. I would suggest PEX or GroupManager.
Then, create a new group with all the permission nodes for what you want the player to have access too, and assign the player to the group.
**For GroupManager:** _(A little bit easier to use than PEX)_
**1.** Do /mangadd [any name]
**2.** Do /mangaddp [the group you created above] [the permission you want the player/group to have]
**3.** Do step 2 as many times as you need, until all the permissions you want are in the group. _(You can do this in the config for GroupManager too but this is the simplest way)_
**4.** Do /manuadd [player you want to have the permissions] [group you created above]

I hope this solves your problem, however if it didn't, please let me know and I can provide further help!

**Comment by deezaath** [comment]
Thanks! :D
