### ISSUE TITLE
errors 1.14 No commands work "No lang file found!"

### ISSUE THREAD

**Issue by Abyss-ora** [bluecreeper111/JEssentials#20]
[00:08:55] [Server thread/INFO]: Tybalt85 issued server command: /fly
--
68 | [00:08:55] [Server thread/ERROR]: No lang file found! Please install one from our github.
69 | [00:08:55] [Server thread/ERROR]: null
70 | org.bukkit.command.CommandException: Unhandled exception executing command 'fly' in plugin JEssentials v1.4.1
71 | at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[minecraft_server.jar:git-Bukkit-1fee35b]
72 | at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[minecraft_server.jar:git-Bukkit-1fee35b]
73 | at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:686) ~[minecraft_server.jar:git-Bukkit-1fee35b]
74 | at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1615) ~[minecraft_server.jar:git-Bukkit-1fee35b]
75 | at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1469) ~[minecraft_server.jar:git-Bukkit-1fee35b]
76 | at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(SourceFile:37) ~[minecraft_server.jar:git-Bukkit-1fee35b]
77 | at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(SourceFile:9) ~[minecraft_server.jar:git-Bukkit-1fee35b]
78 | at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[minecraft_server.jar:git-Bukkit-1fee35b]
79 | at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [minecraft_server.jar:git-Bukkit-1fee35b]
80 | at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [minecraft_server.jar:git-Bukkit-1fee35b]
81 | at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [minecraft_server.jar:git-Bukkit-1fee35b]
82 | at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [minecraft_server.jar:git-Bukkit-1fee35b]
83 | at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:853) [minecraft_server.jar:git-Bukkit-1fee35b]
84 | at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:846) [minecraft_server.jar:git-Bukkit-1fee35b]
85 | at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:123) [minecraft_server.jar:git-Bukkit-1fee35b]
86 | at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:830) [minecraft_server.jar:git-Bukkit-1fee35b]
87 | at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:770) [minecraft_server.jar:git-Bukkit-1fee35b]
88 | at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
89 | Caused by: java.lang.IllegalArgumentException: Cannot translate null text
90 | at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[minecraft_server.jar:git-Bukkit-1fee35b]
91 | at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:217) ~[minecraft_server.jar:git-Bukkit-1fee35b]
92 | at com.bluecreeper111.jessentials.api.api.translateColor(api.java:151) ~[?:?]
93 | at com.bluecreeper111.jessentials.api.api.getLangString(api.java:184) ~[?:?]
94 | at com.bluecreeper111.jessentials.api.api.noPermission(api.java:22) ~[?:?]
95 | at com.bluecreeper111.jessentials.commands.Fly.onCommand(Fly.java:23) ~[?:?]
96 | at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[minecraft_server.jar:git-Bukkit-1fee35b]
97 | ... 17 more

Using Aternos
https://aternos.org/addons/a/spigot/65288
No lang file found! Please install one from our github.
Aternos does not let you install files.

https://mclo.gs/7tOYE1P
To see the full log.

**Comment by EmbodiedYeti** [comment]
Using Aternos
https://aternos.org/addons/a/spigot/65288
No lang file found! Please install one from our github.
Aternos does not let you install files.

**Comment by EmbodiedYeti** [comment]
https://mclo.gs/7tOYE1P
To see the full log.

**Comment by jeremy-carefoot** [comment]
Please install the plugin Vault, or else the lang.yml file will not generate properly. It is a dependency of the plugin.
