### ISSUE TITLE
Command /home uses tpDelayMessage

### ISSUE THREAD

**Issue by avalon666** [bluecreeper111/JEssentials#22]
The command /home outputs the text of "tpDelayMessage: '&6Teleporting in &c%delay% &6seconds''".
This will cause the teleport to be executed from Home after 3 seconds.

**Comment by jeremy-carefoot** [comment]
You can disable/change teleport delay times inside of the config.yml file. Or, alternatively, you can give all players the permission jessentials.teleport.delay.bypass . For future support, I would recommend joining our Discord :).

**Comment by avalon666** [comment]
The teleport delay is desired. The displayed message is wrong. It should be a separate message alias _homeDelayMessage_.
Because of Discord, I don't speak English. This is all translated. :-D
