### ISSUE TITLE
Null Chat Setup (1.14.1)

### ISSUE THREAD

**Issue by ghost** [bluecreeper111/JEssentials#26]
I'm trying to code and import chat, permissions and economy from Vault for 1.14.1, and everything seems to work except chat.

Error log: https://pastebin.com/N4PRffwc

Setup Code: https://pastebin.com/rfmKVWPL (cut a bit that is unrelated)

Chat Message Event: https://pastebin.com/wa4duxtu

I'm not quite sure why the chat setup is null, I've tried different types of chat setups but it doesn't seem to want to work.

**Comment by jeremy-carefoot** [comment]
Create a public static Chat method which returns Chat in your main class. If you followed the Vault tutorial, then your chat will be private static and unable to be accessed in a static way.
Please keep in mind this GitHub is for JEssentials-related issues.

**Comment by ghost** [comment]
My bad, thank you for the help!
