### ISSUE TITLE
"No lang file found! Please install one from our github"

### ISSUE THREAD

**Issue by ghost** [bluecreeper111/JEssentials#3]
Could you help with this? I don't quite understand what I missed or where to get/install this file.

**Comment by jeremy-carefoot** [comment]
This means that you have an error in your lang.yml file. Ignore the download on github part. The lang.yml file is what contains all the messages in the plugin.  
To generate a new lang.yml file:  
**1.** Stop your server  
**2.** Delete your current lang.yml file (In same folder as config)  
**3.** Start  your server  
If your error persists, please let me know.

**Comment by ghost** [comment]
Hey so I looked and I just do not have a lang.yml file anywhere. I use multicraft and i went to file manager and it's not in with the other yml's. Could you provide a download for it?

**Comment by jeremy-carefoot** [comment]
> Hey so I looked and I just do not have a lang.yml file anywhere. I use multicraft and i went to file manager and it's not in with the other yml's. Could you provide a download for it?

https://www.dropbox.com/s/t2q893p8hs9yhbs/lang.yml?dl=0

**Comment by jeremy-carefoot** [comment]
After some bug testing, I have found that this is an error with JEssentials V1.3.3
As a temporary solution, download the lang.yml file from above.

**Comment by jeremy-carefoot** [comment]
Bug has been fixed in JEssentials V1.3.4

**Comment by ghost** [comment]
when is V1.3.4 going to be released?

**Comment by ghost** [comment]
Sorry i know it's on your github i meant on bukkit org. Do you mind updating when you get a chance, Im using multicraft and it can only use the bukkit org file for easy install
