### ISSUE TITLE
Vanish No Packet issue #2

### ISSUE THREAD

**Issue by masonmanley** [bluecreeper111/JEssentials#37]
Please could you add support for Vanish No Packet so that teleports are hidden from players when they are vanished in Vanish No Packet?

Thanks :)

**Comment by jeremy-carefoot** [comment]
Thank you for the suggestion, however I would like to encourage players to use JEssentials vanish instead, and this would compete against that. For the next update I am trying to allow the user to disable certain commands so other plugins can take higher priority. (To address your other issue).
