### ISSUE TITLE
Sethome bug

### ISSUE THREAD

**Issue by notbonjubuemos** [bluecreeper111/JEssentials#38]
I run a small server and there seems to be a bug with setting homes. For some people when they do /sethome <home name> the console says that they have set the max number of homes. This happens when they have less than 3 homes, which is the maximum number of homes. It seems to be caused by one of their homes being blank with no name. Any idea how to fix this?

Thanks.

**Comment by jeremy-carefoot** [comment]
I have noticed alot of bugs revolving homes right now and I would just recommend deleting your homes.yml file and restarting your server.
