### ISSUE TITLE
 Could not pass event PlayerJoinEvent to JEssentials v1.5.1

### ISSUE THREAD

**Issue by naisencu** [bluecreeper111/JEssentials#40]
My server seems to be having an issue it shows an error , sorry I don't understand any coding so its hard for me to describe what error I am facing, Here's the server log
Note that I'm running Bukkit/spigot 1.14 version.
I've cut the full server log coz its too long, so I'm showing only the error log . If u need the full log then I can paste it fully l8r. I'm also running the 4.0.0 version of your plugin. 

[10:36:56] [Server thread/INFO]: Welcome HowieTP to the server for the first time!
--
411 | [10:36:56] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to JEssentials v1.5.1
412 | org.bukkit.event.EventException: null
413 | at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[minecraft_server.jar:git-Spigot-c8d4cef-1fee35b]
414 | at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[minecraft_server.jar:git-Spigot-c8d4cef-1fee35b]
415 | at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) [minecraft_server.jar:git-Spigot-c8d4cef-1fee35b]
416 | at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) [minecraft_server.jar:git-Spigot-c8d4cef-1fee35b]
417 | at net.minecraft.server.v1_14_R1.PlayerList.a(PlayerList.java:173) [minecraft_server.jar:git-Spigot-c8d4cef-1fee35b]
418 | at net.minecraft.server.v1_14_R1.LoginListener.c(LoginListener.java:149) [minecraft_server.jar:git-Spigot-c8d4cef-1fee35b]
419 | at net.minecraft.server.v1_14_R1.LoginListener.tick(LoginListener.java:53) [minecraft_server.jar:git-Spigot-c8d4cef-1fee35b]
420 | at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:230) [minecraft_server.jar:git-Spigot-c8d4cef-1fee35b]
421 | at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:119) [minecraft_server.jar:git-Spigot-c8d4cef-1fee35b]
422 | at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1080) [minecraft_server.jar:git-Spigot-c8d4cef-1fee35b]
423 | at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [minecraft_server.jar:git-Spigot-c8d4cef-1fee35b]
424 | at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:956) [minecraft_server.jar:git-Spigot-c8d4cef-1fee35b]
425 | at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801) [minecraft_server.jar:git-Spigot-c8d4cef-1fee35b]
426 | at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
427 | Caused by: java.lang.NullPointerException
428 | at com.bluecreeper111.jessentials.commands.Kit.onJoin(Kit.java:319) ~[?:?]
429 | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
430 | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202]
431 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]
432 | at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]
433 | at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[minecraft_server.jar:git-Spigot-c8d4cef-1fee35b]
434 | ... 13 more

**Comment by jeremy-carefoot** [comment]
This is an issue regarding giving players a kit on join, and seems to always appear for no reason. Don't worry though, as this will be fixed in the next update. Until then, there is nothing you can do.
