### ISSUE TITLE
Could not pass event AsyncPlayerChatEvent to JEssentials v1.5.9

### ISSUE THREAD

**Issue by naisencu** [bluecreeper111/JEssentials#43]
This is the error log on my server, I don't know what's happening but I'm guessing that it is connected to the chatting system. I've added luckperms,vault to my server and I have set my rank to be admin. When I give an admin prefix, it doesn't show in the chat log whenever i type. It only appears like this : <baldy1> test with no colour whatsoever. I checked whether my prefix and suffix was added or not and I did /lp user baldy1 info and it shows parent group admin and also the correct prefix and suffix. I also have enabled the per-group-formatting to be true

Here's the error log : 

377 | [09:07:04] [Async Chat Thread - #0/ERROR]: Could not pass event AsyncPlayerChatEvent to JEssentials v1.5.9
378 | org.bukkit.event.EventException: null
379 | at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[minecraft_server.jar:git-Spigot-c8d4cef-1fee35b]
380 | at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[minecraft_server.jar:git-Spigot-c8d4cef-1fee35b]
381 | at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) [minecraft_server.jar:git-Spigot-c8d4cef-1fee35b]
382 | at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [minecraft_server.jar:git-Spigot-c8d4cef-1fee35b]
383 | at net.minecraft.server.v1_14_R1.PlayerConnection.chat(PlayerConnection.java:1588) [minecraft_server.jar:git-Spigot-c8d4cef-1fee35b]
384 | at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1526) [minecraft_server.jar:git-Spigot-c8d4cef-1fee35b]
385 | at net.minecraft.server.v1_14_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) [minecraft_server.jar:git-Spigot-c8d4cef-1fee35b]
386 | at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_202]
387 | at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_202]
388 | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202]
389 | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_202]
390 | at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
391 | Caused by: java.lang.NullPointerException
392 | at me.lucko.luckperms.bukkit.vault.LuckPermsVaultPermission.contextForLookup(LuckPermsVaultPermission.java:400) ~[?:?]
393 | at me.lucko.luckperms.bukkit.vault.LuckPermsVaultChat.getGroupChatPrefix(LuckPermsVaultChat.java:167) ~[?:?]
394 | at me.lucko.luckperms.bukkit.vault.AbstractVaultChat.getGroupPrefix(AbstractVaultChat.java:248) ~[?:?]
395 | at com.bluecreeper111.jessentials.event.playerChat.onPlayerChat(playerChat.java:47) ~[?:?]
396 | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
397 | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202]
398 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]
399 | at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]
400 | at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[minecraft_server.jar:git-Spigot-c8d4cef-1fee35b]
401 | ... 11 more

**Comment by jeremy-carefoot** [comment]
Looking into this for the next update.

**Comment by dabudke** [comment]
I am experiencing this issue too, any versions that don't have this issue?

**Comment by Chriisuuuu** [comment]
also experiencing this, server is in offline mode though, so that may have something to do with it. may be a problem with LP/Vault as ChatManager also experiences it, atleast on my server
