### ISSUE TITLE
Error occurred while enabling Essentials

### ISSUE THREAD

**Issue by EduBRz** [bluecreeper111/JEssentials#48]
version JEssentials V1.5.9
---------------------------------------------log-------------------------------------------------
20:18:00 [INFO] [BssentialsEssentialsBridge]: Method not implemented: com.earth2me.essentials.I18n#onEnable
20:18:00 [INFO] [BssentialsEssentialsBridge]: Method not implemented: com.earth2me.essentials.Console#setInstance
20:18:00 [Server thread/ERROR]: Error occurred while enabling Essentials v2.0.1-Bssentials (Is it up to date?)
20:18:00 java.lang.NullPointerException: null
20:18:00 	at java.io.Reader.<init>(Reader.java:78) ~[?:1.8.0_51]
20:18:00 	at java.io.InputStreamReader.<init>(InputStreamReader.java:72) ~[?:1.8.0_51]
20:18:00 	at com.earth2me.essentials.ManagedFile.copyResourceAscii(ManagedFile.java:49) ~[?:?]
20:18:00 	at com.earth2me.essentials.ManagedFile.<init>(ManagedFile.java:41) ~[?:?]
20:18:00 	at com.earth2me.essentials.ItemDb.<init>(ItemDb.java:43) ~[?:?]
20:18:00 	at com.earth2me.essentials.Essentials.onEnable(Essentials.java:215) ~[?:?]
20:18:00 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-8003ced]
20:18:00 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.14.2.jar:git-Spigot-df0eb25-8003ced]
20:18:00 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416) [spigot-1.14.2.jar:git-Spigot-df0eb25-8003ced]
20:18:00 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:458) [spigot-1.14.2.jar:git-Spigot-df0eb25-8003ced]
20:18:00 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:372) [spigot-1.14.2.jar:git-Spigot-df0eb25-8003ced]
20:18:00 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:440) [spigot-1.14.2.jar:git-Spigot-df0eb25-8003ced]
20:18:00 	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258) [spigot-1.14.2.jar:git-Spigot-df0eb25-8003ced]
20:18:00 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:761) [spigot-1.14.2.jar:git-Spigot-df0eb25-8003ced]
20:18:00 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]

**Comment by bjorno43** [comment]
This is not a JEssentials plugin. `Error occurred while enabling Essentials v2.0.1` <--

You are either using the wrong plugin or modified ours. In both cases we're unable to help you solve this issue.
