### ISSUE TITLE
Buy/Sell Signs Do Not Recognize Some Items

### ISSUE THREAD

**Issue by mhypnaro** [bluecreeper111/JEssentials#50]
```
[Buy]
32
SPRUCE_LOG
80

[Buy]
32
spruce_log
80

[Buy]
32
Spruce_Log
80
```

I have tried many different variations of the item ids listed in the official Bukkit Materials list, but the sign only gives me the following error.

"Error occurred while using sign: Invalid item!"

This isn't just for Spruce Logs, it affects a lot of items.

**Comment by mhypnaro** [comment]
This also appears to be happening with the /item command.

Perhaps there is something wrong with my installation of Spigot instead?

**Comment by jeremy-carefoot** [comment]
Don't fear, there is nothing wrong on your end. Our team is aware of this issue and actively working to fix it. It isn't really a problem with JEssentials, but more a problem with the Spigot API instead. We are hoping to reach a resolution soon. Thanks for reporting!
