### ISSUE TITLE
Kit issues

### ISSUE THREAD

**Issue by TannerDelta** [bluecreeper111/JEssentials#53]
[latest.log](https://github.com/bluecreeper111/JEssentials/files/3331962/latest.log)
Trying to load a kit only displays that an internal error has occured when I run the command.
Also, I can't delete a kit marked as starter as it says it can't be found, but shows up in the kit list

**Comment by jeremy-carefoot** [comment]
Please be sure your lang.yml file isn't corrupt. You can check this by deleting it and restarting your server.
