### ISSUE TITLE
Made an edit to the lang.yml and now there's an internal error

### ISSUE THREAD

**Issue by OakStairs** [bluecreeper111/JEssentials#54]
I'm pretty sure a lot of people are reporting on this issue, but I changed the wording to better fit my server on the lang.yml. Kept all the correct formatting, went down the line and made sure every ' was put before and after each phrase. Even added color to each. 

This is the log I get every time I restart my server: https://pastebin.com/rCmNTBhC

UPDATE: It's not letting me run any world edit commands whatsoever, maybe that helps?

**Comment by jeremy-carefoot** [comment]
This is odd and I am pretty sure the worldedit issue has nothing to do with it. While changing the lang.yml file, you didnt change the tag before the actual message did you?

**Comment by OakStairs** [comment]
I might have, but the issue's been resolved in the discord you got going on. Thanks
