### ISSUE TITLE
1.14 - Request - 

### ISSUE THREAD

**Issue by BrandonGamesYT** [bluecreeper111/JEssentials#6]
I know the update just came out but if a possible update for this to 1.14 would be awesome so I could start using this on my server. Thank you!

**Comment by jeremy-carefoot** [comment]
I could look into this.

**Comment by Creepalite** [comment]
Yeah, it would be awesome if we could have a 1.14 version soon. Thank you.

**Comment by jeremy-carefoot** [comment]
Update released. (Currently only available on Spigot)
