### ISSUE TITLE
PermissionEX and Jessentials not working togheter. Server crashes

### ISSUE THREAD

**Issue by Sebas-Re** [bluecreeper111/JEssentials#7]
Hello!
         So, my problem is that every time i open the game with PermissionEX and Jessentials enabled, the server dies when i log in.
        Because of that, i disabled AuthMe just to see if that was the problem, but i ended up with the conclusion that, for some reason, they won't get on well.
The error is in the file below:
[error.txt](https://github.com/bluecreeper111/JEssentials/files/3132870/error.txt)

**Comment by jeremy-carefoot** [comment]
I have just released an update on spigot that opens support to MC 1.14 and fixes alot of bugs. Try that version, and if the bug still isn't fixed please let me know and I will reopen this issue.
