### ISSUE TITLE
TP'ing to players in gmsp gives players a teleporting self to self

### ISSUE THREAD

**Issue by x0bre** [bluecreeper111/JEssentials#8]
I run a new 1.14 server and have players coming in, I'm quite involved in the "hacked client" community and know clients are already out there. So to run my server I go around in Spectator to check up on new players, but when I teleport it gives them a message in chat. This is really suspicious to them and some of them just stop moving altogether, and makes it hard to find the sneaky ones who catch on. Is there something in the config to change this, or a way to use the default /tp command?

**Comment by x0bre** [comment]
/tpo (name) works fine but it also spits errors

**Comment by masonmanley** [comment]
I also get this. /tp shows player a message saying they are teleporting to themselves
